batch_size: 8
dataset:
  _component_: custom_dataset
device: cuda
epochs: 15
model:
  _component_: torchtune.models.llama3_2.llama3_2_1b
optimizer:
  _component_: bitsandbytes.optim.PagedAdamW8bit
  lr: 3.0e-05
output_dir: /tmp/finetune_results
